begin;
select plan(7);
select has_function('public', 'prepare_memory_photo_upload', array['uuid','uuid','text']);
select has_function('public', 'complete_memory_photo_upload', array['uuid']);
select has_function('public', 'delete_memory_photo', array['uuid']);
select has_column('public', 'memory_photos', 'upload_request_key', 'photos store an idempotency key');
select has_column('public', 'memory_photos', 'mime_type', 'photos store their MIME type');
select has_column('public', 'memory_photos', 'status', 'photos store upload state');
select ok(exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'memory_photos_read_authorized_viewer'), 'memory photos restrict reads to authorized viewers');
select * from finish();
rollback;
