-- Generated from src/catalog/items.ts. Run npm run catalog:seed to refresh.
begin;

insert into public.room_slots (id, name_ko, zone)
values
  ('window', '창가 커튼 자리', 'wall'),
  ('center-table', '가운데 탁자 자리', 'floor'),
  ('floor-accent-left', '왼쪽 포근 자리', 'floor'),
  ('floor-accent-right', '오른쪽 포근 자리', 'floor'),
  ('floor-rug', '바닥 러그 자리', 'floor'),
  ('bed-corner', '침대 모서리', 'floor'),
  ('light-left', '왼쪽 조명 자리', 'floor'),
  ('light-right', '오른쪽 조명 자리', 'floor'),
  ('plant-corner', '식물 모서리', 'floor'),
  ('animal-use', '동물 사용 아이템', 'animal'),
  ('memory-wall', '추억 벽 자리', 'wall'),
  ('memory-shelf', '추억 선반 자리', 'shelf')
on conflict (id) do update
set name_ko = excluded.name_ko,
    zone = excluded.zone;

insert into public.item_definitions (
  id, source, category, theme, name_ko, price, consumable, thumbnail_key, room_asset_key,
  silhouette, size, anchor, allowed_slot_ids, layer_bias, interaction, asset_status, preview_color, active
)
values
  ('curtain-ribbon-pair', 'shop', 'curtain', 'sunny', '햇살 리본 커튼', 320, false, 'illustrated:furniture:curtain-sunlight-ribbon', 'illustrated:furniture:curtain-sunlight-ribbon', 'ribbon-pair', '{"width":260,"height":250}'::jsonb, '{"x":130,"y":250}'::jsonb, '["window"]'::jsonb, -20, 'none', 'final', '#F4C6A8', true),
  ('curtain-cloud-valance', 'shop', 'curtain', 'forest', '구름 주름 커튼', 340, false, 'illustrated:furniture:curtain-cloud-valance', 'illustrated:furniture:curtain-cloud-valance', 'cloud-valance', '{"width":260,"height":250}'::jsonb, '{"x":130,"y":250}'::jsonb, '["window"]'::jsonb, -20, 'none', 'final', '#B9D8EC', true),
  ('curtain-leaf-panels', 'shop', 'curtain', 'cloud', '숲잎 커튼', 360, false, 'illustrated:furniture:curtain-leaf-panels', 'illustrated:furniture:curtain-leaf-panels', 'leaf-panels', '{"width":260,"height":250}'::jsonb, '{"x":130,"y":250}'::jsonb, '["window"]'::jsonb, -20, 'none', 'final', '#A8D2B4', true),
  ('curtain-star-drape', 'shop', 'curtain', 'night', '별밤 커튼', 380, false, 'illustrated:furniture:curtain-star-drape', 'illustrated:furniture:curtain-star-drape', 'star-drape', '{"width":260,"height":250}'::jsonb, '{"x":130,"y":250}'::jsonb, '["window"]'::jsonb, -20, 'none', 'final', '#B9ACD8', true),
  ('curtain-cafe-check', 'shop', 'curtain', 'picnic', '체크 카페 커튼', 400, false, 'illustrated:furniture:curtain-cafe-check', 'illustrated:furniture:curtain-cafe-check', 'cafe-check', '{"width":260,"height":250}'::jsonb, '{"x":130,"y":250}'::jsonb, '["window"]'::jsonb, -20, 'none', 'final', '#EAA6A1', true),
  ('table-round-cookie', 'shop', 'table', 'sunny', '둥근 쿠키 탁자', 450, false, 'illustrated:furniture:table-cookie', 'illustrated:furniture:table-cookie', 'round-cookie', '{"width":280,"height":190}'::jsonb, '{"x":140,"y":180}'::jsonb, '["center-table"]'::jsonb, 0, 'eat', 'final', '#CFA77C', true),
  ('table-tulip-pedestal', 'shop', 'table', 'forest', '튤립 찻상', 470, false, 'illustrated:furniture:table-tulip-pedestal', 'illustrated:furniture:table-tulip-pedestal', 'tulip-pedestal', '{"width":280,"height":190}'::jsonb, '{"x":140,"y":180}'::jsonb, '["center-table"]'::jsonb, 0, 'eat', 'final', '#EFA7A7', true),
  ('table-cloud-low', 'shop', 'table', 'cloud', '구름 낮은 탁자', 490, false, 'illustrated:furniture:table-cloud-low', 'illustrated:furniture:table-cloud-low', 'cloud-low', '{"width":280,"height":190}'::jsonb, '{"x":140,"y":180}'::jsonb, '["center-table"]'::jsonb, 0, 'eat', 'final', '#B8D8E9', true),
  ('table-shelf-table', 'shop', 'table', 'night', '책장 겸용 탁자', 510, false, 'illustrated:furniture:table-shelf', 'illustrated:furniture:table-shelf', 'shelf-table', '{"width":280,"height":190}'::jsonb, '{"x":140,"y":180}'::jsonb, '["center-table"]'::jsonb, 0, 'eat', 'final', '#B89270', true),
  ('table-clover-table', 'shop', 'table', 'picnic', '네잎 식탁', 530, false, 'illustrated:furniture:table-clover', 'illustrated:furniture:table-clover', 'clover-table', '{"width":280,"height":190}'::jsonb, '{"x":140,"y":180}'::jsonb, '["center-table"]'::jsonb, 0, 'eat', 'final', '#93C7A5', true),
  ('cushion-shell', 'shop', 'cushion', 'sunny', '복숭아 조개 쿠션', 180, false, 'illustrated:furniture:cushion-shell', 'illustrated:furniture:cushion-shell', 'shell', '{"width":140,"height":90}'::jsonb, '{"x":70,"y":82}'::jsonb, '["floor-accent-left","floor-accent-right"]'::jsonb, 2, 'rest', 'final', '#F2A98C', true),
  ('cushion-knot', 'shop', 'cushion', 'forest', '민트 매듭 쿠션', 200, false, 'illustrated:furniture:cushion-mint-knot', 'illustrated:furniture:cushion-mint-knot', 'knot', '{"width":140,"height":90}'::jsonb, '{"x":70,"y":82}'::jsonb, '["floor-accent-left","floor-accent-right"]'::jsonb, 2, 'rest', 'final', '#91C9AF', true),
  ('cushion-star', 'shop', 'cushion', 'cloud', '별 쿠션', 220, false, 'illustrated:furniture:cushion-star', 'illustrated:furniture:cushion-star', 'star', '{"width":140,"height":90}'::jsonb, '{"x":70,"y":82}'::jsonb, '["floor-accent-left","floor-accent-right"]'::jsonb, 2, 'rest', 'final', '#E6C66E', true),
  ('cushion-cloud', 'shop', 'cushion', 'night', '구름 쿠션', 240, false, 'illustrated:furniture:cushion-cloud', 'illustrated:furniture:cushion-cloud', 'cloud', '{"width":140,"height":90}'::jsonb, '{"x":70,"y":82}'::jsonb, '["floor-accent-left","floor-accent-right"]'::jsonb, 2, 'rest', 'final', '#C3DDEE', true),
  ('cushion-petal', 'shop', 'cushion', 'picnic', '꽃잎 방석', 260, false, 'illustrated:furniture:cushion-petal', 'illustrated:furniture:cushion-petal', 'petal', '{"width":140,"height":90}'::jsonb, '{"x":70,"y":82}'::jsonb, '["floor-accent-left","floor-accent-right"]'::jsonb, 2, 'rest', 'final', '#D9A9C4', true),
  ('rug-soft-oval', 'shop', 'rug', 'sunny', '포근 타원 러그', 360, false, 'illustrated:furniture:rug-soft-oval', 'illustrated:furniture:rug-soft-oval', 'soft-oval', '{"width":550,"height":170}'::jsonb, '{"x":275,"y":145}'::jsonb, '["floor-rug"]'::jsonb, -10, 'none', 'final', '#D8B891', true),
  ('rug-wavy', 'shop', 'rug', 'forest', '물결 러그', 380, false, 'illustrated:furniture:rug-wavy', 'illustrated:furniture:rug-wavy', 'wavy', '{"width":550,"height":170}'::jsonb, '{"x":275,"y":145}'::jsonb, '["floor-rug"]'::jsonb, -10, 'none', 'final', '#91C5D8', true),
  ('rug-daisy', 'shop', 'rug', 'cloud', '데이지 러그', 400, false, 'illustrated:furniture:rug-daisy', 'illustrated:furniture:rug-daisy', 'daisy', '{"width":550,"height":170}'::jsonb, '{"x":275,"y":145}'::jsonb, '["floor-rug"]'::jsonb, -10, 'none', 'final', '#E8C96F', true),
  ('rug-picnic-check', 'shop', 'rug', 'night', '체크 피크닉 러그', 420, false, 'illustrated:furniture:rug-picnic-check', 'illustrated:furniture:rug-picnic-check', 'picnic-check', '{"width":550,"height":170}'::jsonb, '{"x":275,"y":145}'::jsonb, '["floor-rug"]'::jsonb, -10, 'none', 'final', '#E8A59B', true),
  ('rug-forest-path', 'shop', 'rug', 'picnic', '숲길 러그', 440, false, 'illustrated:furniture:rug-forest-path', 'illustrated:furniture:rug-forest-path', 'forest-path', '{"width":550,"height":170}'::jsonb, '{"x":275,"y":145}'::jsonb, '["floor-rug"]'::jsonb, -10, 'none', 'final', '#92B78F', true),
  ('bed-moon-headboard', 'shop', 'bed', 'sunny', '달잠 침대', 520, false, 'illustrated:furniture:bed-moon-sleep', 'illustrated:furniture:bed-moon-sleep', 'moon-headboard', '{"width":300,"height":230}'::jsonb, '{"x":150,"y":220}'::jsonb, '["bed-corner"]'::jsonb, 1, 'rest', 'final', '#AFA9D5', true),
  ('bed-log-bed', 'shop', 'bed', 'forest', '통나무 침대', 540, false, 'illustrated:furniture:bed-log', 'illustrated:furniture:bed-log', 'log-bed', '{"width":300,"height":230}'::jsonb, '{"x":150,"y":220}'::jsonb, '["bed-corner"]'::jsonb, 1, 'rest', 'final', '#B68D67', true),
  ('bed-cloud-nest', 'shop', 'bed', 'cloud', '구름 둥지', 560, false, 'illustrated:furniture:bed-cloud-nest', 'illustrated:furniture:bed-cloud-nest', 'cloud-nest', '{"width":300,"height":230}'::jsonb, '{"x":150,"y":220}'::jsonb, '["bed-corner"]'::jsonb, 1, 'rest', 'final', '#C8DCE8', true),
  ('bed-berry-canopy', 'shop', 'bed', 'night', '딸기 캐노피', 580, false, 'illustrated:furniture:bed-berry-canopy', 'illustrated:furniture:bed-berry-canopy', 'berry-canopy', '{"width":300,"height":230}'::jsonb, '{"x":150,"y":220}'::jsonb, '["bed-corner"]'::jsonb, 1, 'rest', 'final', '#E99A9C', true),
  ('bed-bookcase-bed', 'shop', 'bed', 'picnic', '책장 침대', 600, false, 'illustrated:furniture:bed-bookcase', 'illustrated:furniture:bed-bookcase', 'bookcase-bed', '{"width":300,"height":230}'::jsonb, '{"x":150,"y":220}'::jsonb, '["bed-corner"]'::jsonb, 1, 'rest', 'final', '#D2AA78', true),
  ('lighting-firefly-stand', 'shop', 'lighting', 'sunny', '반딧불 스탠드', 280, false, 'illustrated:furniture:lighting-firefly-stand', 'illustrated:furniture:lighting-firefly-stand', 'firefly-stand', '{"width":120,"height":230}'::jsonb, '{"x":60,"y":220}'::jsonb, '["light-left","light-right"]'::jsonb, 1, 'none', 'final', '#E9CA6F', true),
  ('lighting-mushroom-lamp', 'shop', 'lighting', 'forest', '버섯 조명', 300, false, 'illustrated:furniture:lighting-mushroom', 'illustrated:furniture:lighting-mushroom', 'mushroom-lamp', '{"width":120,"height":230}'::jsonb, '{"x":60,"y":220}'::jsonb, '["light-left","light-right"]'::jsonb, 1, 'none', 'final', '#E6A186', true),
  ('lighting-cloud-pendant', 'shop', 'lighting', 'cloud', '구름 펜던트', 320, false, 'illustrated:furniture:lighting-cloud-pendant', 'illustrated:furniture:lighting-cloud-pendant', 'cloud-pendant', '{"width":120,"height":230}'::jsonb, '{"x":60,"y":220}'::jsonb, '["light-left","light-right"]'::jsonb, 1, 'none', 'final', '#B8D8E9', true),
  ('lighting-constellation', 'shop', 'lighting', 'night', '별자리 무드등', 340, false, 'illustrated:furniture:lighting-constellation', 'illustrated:furniture:lighting-constellation', 'constellation', '{"width":120,"height":230}'::jsonb, '{"x":60,"y":220}'::jsonb, '["light-left","light-right"]'::jsonb, 1, 'none', 'final', '#AFA8D7', true),
  ('lighting-tulip-lamp', 'shop', 'lighting', 'picnic', '튤립 램프', 360, false, 'illustrated:furniture:lighting-tulip', 'illustrated:furniture:lighting-tulip', 'tulip-lamp', '{"width":120,"height":230}'::jsonb, '{"x":60,"y":220}'::jsonb, '["light-left","light-right"]'::jsonb, 1, 'none', 'final', '#EAA0AF', true),
  ('plant-round-rubber-tree', 'shop', 'plant', 'sunny', '동글 고무나무', 240, false, 'illustrated:furniture:plant-rubber-tree', 'illustrated:furniture:plant-rubber-tree', 'round-rubber-tree', '{"width":150,"height":230}'::jsonb, '{"x":75,"y":220}'::jsonb, '["plant-corner"]'::jsonb, 1, 'none', 'final', '#83B598', true),
  ('plant-hanging-ivy', 'shop', 'plant', 'forest', '매달린 아이비', 260, false, 'illustrated:furniture:plant-hanging-ivy', 'illustrated:furniture:plant-hanging-ivy', 'hanging-ivy', '{"width":150,"height":230}'::jsonb, '{"x":75,"y":220}'::jsonb, '["plant-corner"]'::jsonb, 1, 'none', 'final', '#76AA86', true),
  ('plant-cactus-trio', 'shop', 'plant', 'cloud', '선인장 친구', 280, false, 'illustrated:furniture:plant-cactus-trio', 'illustrated:furniture:plant-cactus-trio', 'cactus-trio', '{"width":150,"height":230}'::jsonb, '{"x":75,"y":220}'::jsonb, '["plant-corner"]'::jsonb, 1, 'none', 'final', '#8FBD8D', true),
  ('plant-flower-pot', 'shop', 'plant', 'night', '꽃핀 화분', 300, false, 'illustrated:furniture:plant-flower-pot', 'illustrated:furniture:plant-flower-pot', 'flower-pot', '{"width":150,"height":230}'::jsonb, '{"x":75,"y":220}'::jsonb, '["plant-corner"]'::jsonb, 1, 'none', 'final', '#D59AB2', true),
  ('plant-mini-palm', 'shop', 'plant', 'picnic', '작은 야자수', 320, false, 'illustrated:furniture:plant-mini-palm', 'illustrated:furniture:plant-mini-palm', 'mini-palm', '{"width":150,"height":230}'::jsonb, '{"x":75,"y":220}'::jsonb, '["plant-corner"]'::jsonb, 1, 'none', 'final', '#78B99A', true),
  ('snack-carrot-stars', 'shop', 'snack', 'sunny', '당근 별사탕', 80, true, 'illustrated:furniture:snack-carrot-stars', 'illustrated:furniture:snack-carrot-stars', 'carrot-stars', '{"width":84,"height":64}'::jsonb, '{"x":42,"y":56}'::jsonb, '["animal-use"]'::jsonb, 4, 'eat', 'final', '#EFA26F', true),
  ('snack-acorn-cookie', 'shop', 'snack', 'forest', '꿀밤 쿠키', 100, true, 'illustrated:furniture:snack-acorn-cookie', 'illustrated:furniture:snack-acorn-cookie', 'acorn-cookie', '{"width":84,"height":64}'::jsonb, '{"x":42,"y":56}'::jsonb, '["animal-use"]'::jsonb, 4, 'eat', 'final', '#C89665', true),
  ('snack-fish-cloud', 'shop', 'snack', 'cloud', '생선 구름칩', 120, true, 'illustrated:furniture:snack-fish-cloud', 'illustrated:furniture:snack-fish-cloud', 'fish-cloud', '{"width":84,"height":64}'::jsonb, '{"x":42,"y":56}'::jsonb, '["animal-use"]'::jsonb, 4, 'eat', 'final', '#91BCD4', true),
  ('snack-milk-jelly', 'shop', 'snack', 'night', '딸기 우유젤리', 140, true, 'illustrated:furniture:snack-milk-jelly', 'illustrated:furniture:snack-milk-jelly', 'milk-jelly', '{"width":84,"height":64}'::jsonb, '{"x":42,"y":56}'::jsonb, '["animal-use"]'::jsonb, 4, 'eat', 'final', '#E99CA8', true),
  ('snack-leaf-biscuit', 'shop', 'snack', 'picnic', '민트 잎비스킷', 160, true, 'illustrated:furniture:snack-leaf-biscuit', 'illustrated:furniture:snack-leaf-biscuit', 'leaf-biscuit', '{"width":84,"height":64}'::jsonb, '{"x":42,"y":56}'::jsonb, '["animal-use"]'::jsonb, 4, 'eat', 'final', '#8EC3A7', true),
  ('memory-dining-table-birthday-table', 'memory', 'dining-table', 'celebration', '생일 식탁', 0, false, 'illustrated:memory:birthday-table', 'illustrated:memory:birthday-table', 'birthday-table', '{"width":220,"height":160}'::jsonb, '{"x":110,"y":150}'::jsonb, '["memory-shelf"]'::jsonb, 3, 'memory-detail', 'final', '#E9A08E', true),
  ('memory-dining-table-picnic-table', 'memory', 'dining-table', 'picnic', '소풍 식탁', 0, false, 'illustrated:memory:picnic-table', 'illustrated:memory:picnic-table', 'picnic-table', '{"width":220,"height":160}'::jsonb, '{"x":110,"y":150}'::jsonb, '["memory-shelf"]'::jsonb, 3, 'memory-detail', 'final', '#91B995', true),
  ('memory-dining-table-starlight-table', 'memory', 'dining-table', 'night', '별밤 식탁', 0, false, 'illustrated:memory:starlight-table', 'illustrated:memory:starlight-table', 'starlight-table', '{"width":220,"height":160}'::jsonb, '{"x":110,"y":150}'::jsonb, '["memory-shelf"]'::jsonb, 3, 'memory-detail', 'final', '#AAA5D4', true),
  ('memory-dining-table-brunch-table', 'memory', 'dining-table', 'everyday', '브런치 식탁', 0, false, 'illustrated:memory:brunch-table', 'illustrated:memory:brunch-table', 'brunch-table', '{"width":220,"height":160}'::jsonb, '{"x":110,"y":150}'::jsonb, '["memory-shelf"]'::jsonb, 3, 'memory-detail', 'final', '#E7C47A', true),
  ('memory-dining-table-snow-table', 'memory', 'dining-table', 'seasonal', '눈꽃 식탁', 0, false, 'illustrated:memory:snow-table', 'illustrated:memory:snow-table', 'snow-table', '{"width":220,"height":160}'::jsonb, '{"x":110,"y":150}'::jsonb, '["memory-shelf"]'::jsonb, 3, 'memory-detail', 'final', '#B6D7E7', true),
  ('memory-radio-picnic-radio', 'memory', 'radio', 'celebration', '소풍 라디오', 0, false, 'illustrated:memory:picnic-radio', 'illustrated:memory:picnic-radio', 'picnic-radio', '{"width":220,"height":160}'::jsonb, '{"x":110,"y":150}'::jsonb, '["memory-shelf"]'::jsonb, 3, 'memory-detail', 'final', '#E6A889', true),
  ('memory-radio-night-radio', 'memory', 'radio', 'picnic', '밤하늘 라디오', 0, false, 'illustrated:memory:night-radio', 'illustrated:memory:night-radio', 'night-radio', '{"width":220,"height":160}'::jsonb, '{"x":110,"y":150}'::jsonb, '["memory-shelf"]'::jsonb, 3, 'memory-detail', 'final', '#A9A5D3', true),
  ('memory-radio-forest-radio', 'memory', 'radio', 'night', '숲속 라디오', 0, false, 'illustrated:memory:forest-radio', 'illustrated:memory:forest-radio', 'forest-radio', '{"width":220,"height":160}'::jsonb, '{"x":110,"y":150}'::jsonb, '["memory-shelf"]'::jsonb, 3, 'memory-detail', 'final', '#8DB59A', true),
  ('memory-radio-cassette-radio', 'memory', 'radio', 'everyday', '카세트 라디오', 0, false, 'illustrated:memory:cassette-radio', 'illustrated:memory:cassette-radio', 'cassette-radio', '{"width":220,"height":160}'::jsonb, '{"x":110,"y":150}'::jsonb, '["memory-shelf"]'::jsonb, 3, 'memory-detail', 'final', '#E2BE70', true),
  ('memory-radio-shell-radio', 'memory', 'radio', 'seasonal', '조개 라디오', 0, false, 'illustrated:memory:shell-radio', 'illustrated:memory:shell-radio', 'shell-radio', '{"width":220,"height":160}'::jsonb, '{"x":110,"y":150}'::jsonb, '["memory-shelf"]'::jsonb, 3, 'memory-detail', 'final', '#D7A6BB', true),
  ('memory-frame-ribbon-frame', 'memory', 'frame', 'celebration', '리본 액자', 0, false, 'illustrated:memory:ribbon-frame', 'illustrated:memory:ribbon-frame', 'ribbon-frame', '{"width":150,"height":170}'::jsonb, '{"x":75,"y":160}'::jsonb, '["memory-wall"]'::jsonb, -15, 'memory-detail', 'final', '#E7A2AE', true),
  ('memory-frame-leaf-frame', 'memory', 'frame', 'picnic', '나뭇잎 액자', 0, false, 'illustrated:memory:leaf-frame', 'illustrated:memory:leaf-frame', 'leaf-frame', '{"width":150,"height":170}'::jsonb, '{"x":75,"y":160}'::jsonb, '["memory-wall"]'::jsonb, -15, 'memory-detail', 'final', '#8FB393', true),
  ('memory-frame-cloud-frame', 'memory', 'frame', 'night', '구름 액자', 0, false, 'illustrated:memory:cloud-frame', 'illustrated:memory:cloud-frame', 'cloud-frame', '{"width":150,"height":170}'::jsonb, '{"x":75,"y":160}'::jsonb, '["memory-wall"]'::jsonb, -15, 'memory-detail', 'final', '#ADD2E5', true),
  ('memory-frame-star-frame', 'memory', 'frame', 'everyday', '별 액자', 0, false, 'illustrated:memory:star-frame', 'illustrated:memory:star-frame', 'star-frame', '{"width":150,"height":170}'::jsonb, '{"x":75,"y":160}'::jsonb, '["memory-wall"]'::jsonb, -15, 'memory-detail', 'final', '#D6BA6D', true),
  ('memory-frame-stamp-frame', 'memory', 'frame', 'seasonal', '우표 액자', 0, false, 'illustrated:memory:stamp-frame', 'illustrated:memory:stamp-frame', 'stamp-frame', '{"width":150,"height":170}'::jsonb, '{"x":75,"y":160}'::jsonb, '["memory-wall"]'::jsonb, -15, 'memory-detail', 'final', '#B1A5D1', true)
on conflict (id) do update
set source = excluded.source,
    category = excluded.category,
    theme = excluded.theme,
    name_ko = excluded.name_ko,
    price = excluded.price,
    consumable = excluded.consumable,
    thumbnail_key = excluded.thumbnail_key,
    room_asset_key = excluded.room_asset_key,
    silhouette = excluded.silhouette,
    size = excluded.size,
    anchor = excluded.anchor,
    allowed_slot_ids = excluded.allowed_slot_ids,
    layer_bias = excluded.layer_bias,
    interaction = excluded.interaction,
    asset_status = excluded.asset_status,
    preview_color = excluded.preview_color,
    active = excluded.active;

commit;
